export default theme => ({
    text: {
        fontWeight: 'normal',
        fontStretch: 'normal',
        fontStyle: 'normal',
        lineHeight: 'normal',
        letterSpacing: 'normal',
        textAlign: 'center',
        color: '#ffffff',
    },
    background: {
        backgroundColor: '#506287',
        height: '886px',
    },
    regLabel: {
        width: '143px',
        height: '24px',
        marginLeft: '1283px',
        marginTop: "-610px",
        fontSize: '25px',
        position: 'absolute',
    },
    regBox: {
        width: '510px',
        height: '615px',
        opacity: 0.3,
        border: 'solid 1px #ffffff',
        backgroundColor: '#ffffff',
        marginLeft: '1102px',
        marginTop: '-700px',
    },
    fNameLabel:{
        fontSize: '20px',
        position: 'absolute',
        marginTop: '-560px',
        marginLeft: '1145px',
    },
    lNameLabel: {
        fontSize: '20px',
        position: 'absolute',
        marginTop: '-560px',
        marginLeft: '1355px',
    },
    fNameInput: {
        marginLeft: '1145px',
    },
    lNameInput:{
        marginLeft: '1355px',
    },
    lFName: {
        width: '210px',
        height: '50px',
        border: 'solid 1px #a8a7a7',
        backgroundColor: '#ffffff',
        position: 'absolute',
        marginTop: '-530px',
    },
    genderLabel: {
        height: '16px',
        width: '33px',
        fontSize: '20px',
        color: '#fff',
        position: 'absolute',
        marginTop: '-470px',
        marginLeft: '1145px',
    },
    genderInput: {
        width: '420px',
        height: '50px',
        border: 'solid 1px #a8a7a7',
        backgroundColor: '#ffffff',
        position: 'absolute',
        marginLeft: '1145px',
        marginTop: '-440px',
    },
    loginLabel: {
        fontSize: '20px',
        width: '56px',
        height: '16px',
        color: '#fff',
        position: 'absolute',
        marginTop: '-380px',
        marginLeft: '1145px',
    },
    loginInput: {
        width: '420px',
        height: '50px',
        border: 'solid 1px #a8a7a7',
        backgroundColor: '#ffffff',
        position: 'absolute',
        marginLeft: '1145px',
        marginTop: '-350px',
    },
    emailLabel: {
        fontSize: '20px',
        width: '59px',
        height: '16px',
        color: '#fff',
        position: 'absolute',
        marginTop: '-290px',
        marginLeft: '1145px',
    },
    emailInput: {
        width: '420px',
        height: '50px',
        border: 'solid 1px #a8a7a7',
        backgroundColor: '#ffffff',
        position: 'absolute',
        marginTop: '-260px',
        marginLeft: '1145px',
    },
    passwordLabel: {
        fontSize: '20px',
        width: '59px',
        height: '16px',
        color: '#fff',
        position: 'absolute',
        marginTop: '-200px',
        marginLeft: '1145px',
    },
    passwordInput: {
        width: '420px',
        height: '50px',
        border: 'solid 1px #a8a7a7',
        backgroundColor: '#ffffff',
        position: 'absolute',
        marginTop: '-170px',
        marginLeft: '1145px',
    },
    repeatLabel: {
        fontSize: '20px',
        width: '165px',
        height: '16px',
        color: '#fff',
        position: 'absolute',
        marginTop: '-110px',
        marginLeft: '1145px',
    },
    repeatInput: {
        width: '420px',
        height: '50px',
        border: 'solid 1px #a8a7a7',
        backgroundColor: '#ffffff',
        position: 'absolute',
        marginTop: '-80px',
        marginLeft: '1145px',
    },
    imgSize: {
        height: '790px',
        width: '979px',
        marginLeft: '390px'
    }
});